### PR TITLE
feature/updated-version-and-headless-browser

### PR DESCRIPTION
**Pull request by trinidad8516**
Updated the versions of Cucumber-JVM, plugins, Selenium,  Groovy, Geb, Browser drivers and I added functionality to execute tests as headless for various browsers.

### CODE REVIEW

**Comment by erdi** [comment]
Thanks for the contribution, I will merge it in the next couple of days.

**Comment by trinidad8516** [comment]
@erdi is this a no go?

**Comment by erdi** [comment]
It's a go but I need to do some preparatory work for it around CI because the version of FF used in the docker image is not compatible with your gecko driver version bump. It's just taking more time than I'd like and adds up with other things I'm juggling around the project at the moment. 

Please be patient it's on my todo list and will eventually get merged 😃

**Comment by erdi** [comment]
Thanks for your patience, @trinidad8516!

**Pull request merged**
